# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: f516c082277f38ca0e2d1e93a4b5182e3fabecd525f690f2f3da40a28bfc4a7157a7874fae569379fa5d02075a62498bec4cf16083173afabe929ed876c1e336

test:
  domain_name: glbrc.org
  secret_key_base: 0a2ce1e622d2806efd62d298bcb56f0ed674e0bd49100065b1c21268687100b485e9ab1a1b935ffc18fd2eda2c55c17c2b79067b4dfe5b2191ad865ff325e180

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: glbrc.org
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
